### PR TITLE
homebrew-core's python3 is now 3.6; add python35

### PR DESCRIPTION
**Pull request by dahlia**
The `python3` package in the homebrew-core repsotiroy is now Python 3.6, so we need to add `python3`, a new dead snake!  It's mostly from Formula/python3.rb at homebrew/homebrew-core@510018d362d551e6025cf820f8380ed210955f02.

### CODE REVIEW

**Comment by drolando** [comment]
Can you please also update .travis.yml to install and test python3.5 ?

**Comment by dahlia** [comment]
@drolando Amended!

**Comment by dahlia** [comment]
The [build][1] seems to did fail due to `python27` package.

[1]: https://travis-ci.org/drolando/homebrew-deadsnakes/builds/193884955

**Comment by drolando** [comment]
Master should now be fixed. Rebase and retry

**Comment by dahlia** [comment]
Just rebased it on the latest master!

**Comment by drolando** [comment]
You've lost your changes to .travis.yml in the rebase

**Comment by dahlia** [comment]
That's my fault.  Just restored it!

**Comment by dahlia** [comment]
The [build][1] failed because .travis.yml runs against the upstream master (`brew tap drolando/deadsnakes`). So I fixed (3509cf7b2458ff91e7efbc22c1579e96fa04926c) it to run against the current pull request (if a build is running for a pull request).

[1]: https://travis-ci.org/drolando/homebrew-deadsnakes/builds/194065953

**Comment by drolando** [comment]
Merged. Thanks!

**Pull request merged**
